Consensys/doc.goquorum

.circleci/config.yml
docs/Concepts/Plugins/PluginsArchitecture.md
docs/Concepts/Privacy/ContractExtension.md
docs/HowTo/ManageKeys/AccountPlugins.md

mixed minor formating updates
fixes ConsenSys/doc.goquorum#11
See PR preview at https://pegasys-docgoquorum--13.com.readthedocs.build/en/13/

mixed updates

---

README.md
docs/Concepts/Permissioning/Enhanced/ContractDesign.md

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
Fixed typo

fixed typo in permissioning

---

docs/Concepts/AccountManagement.md
docs/Concepts/NetworkAndChainID.md
docs/Concepts/Privacy/ContractExtension.md
docs/HowTo/Logging and Errors.md

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
minor fixes

minor typos

---

docs/Tutorials/Creating-A-Network-From-Scratch.md

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
This makes the config file valid when you copy the text.

[MINOR] remove vim line from config example

---

.circleci/config.yml

adding docker contexts

---

docs/Concepts/Privacy/Privacy.md
docs/Reference/APIs/PrivacyAPI.md

Clarified eth_storageRoot behaviour

Clarified eth_storageRoot behaviour

---

docs/Concepts/Privacy/PrivacyEnhancements.md

Correct version of Quorum updated

Update release to "CalVer" in documentation

---

docs/Concepts/Privacy/PrivacyEnhancements.md

Updated to include content in response on this Slack thread - https://go-quorum.slack.com/archives/C68NY0QQZ/p1604292913088800

Updated to include examples for privacy enhancements 

---

README.md

Update readme to Consensys repos and update badges
see ConsenSys/protocol-misc#187

update readme and submodule

---

docs/Reference/APIs/PermissioningAPIs.md

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

[MINOR] typos on permissioning API page

---

docs/Reference/APIs/ContractExtensionAPIs.md

* Update out-of-date parameters and responses
* Add `quorumExtension_getExtensionStatus`
* Wording changes

Update quorumExtension API docs

---

docs/Concepts/Plugins/Plugins.md
docs/Concepts/Security/Framework/DecentralizedApplication/FrontendComponents.md
docs/HowTo/Configure/HighAvailability.md
docs/HowTo/GetStarted/Cakeshop.md
docs/HowTo/GetStarted/Install.md
docs/HowTo/GetStarted/Wizard/Interacting.md
docs/HowTo/GetStarted/migration.md
docs/HowTo/ManageKeys/AccountPlugins.md
docs/HowTo/Use/AddingIBFTValidators.md
docs/HowTo/Use/EnhancedPermissions.md
docs/HowTo/Use/JSON-RPC-API-Security.md
docs/HowTo/Use/add_node_examples.md
docs/HowTo/Use/adding_nodes.md
docs/Reference/APIs/ContractExtensionAPIs.md
docs/Reference/APIs/PermissioningAPIs.md
docs/Reference/APIs/PrivacyAPI.md
docs/Reference/APIs/PrivacyEnhancementsAPIs.md
docs/Reference/Consensus/IBFTParameters.md
docs/Reference/Consensus/Raft-RPC-API.md
docs/Reference/FAQ.md
docs/Reference/quorum.js/RawTransactionManager.md
docs/Reference/quorum.js/extend.md
docs/Tutorials/Creating-A-Network-From-Scratch.md
docs/Tutorials/Quorum-Dev-Quickstart.md

- make them able to be copied and pasted without the need to remove any char like `>` or `$` before.
- separate command and result
- Required to rework the tutorial to make it consistent
- fixed code blocks indentation
- applied the correct type for each code block. "text" when no specific formatting, usually in info command outputs.
Check https://pegasys-docgoquorum--39.com.readthedocs.build/en/39/
fixes #38

Update code block to comply with our guidelines

---

docs/Concepts/Consensus/Raft.md
docs/HowTo/GetStarted/Cakeshop.md

Updating links to ConsenSys

---

docs/Tutorials/Adding-removing-IBFT-validators.md
docs/Tutorials/Create-IBFT-Network.md
docs/Tutorials/Create-Privacy-enabled-network.md
docs/Tutorials/CreatePermissionedNetwork.md
mkdocs.yml

Updated IBFT tutorial and split into three topics: 
Create IBFT network
Adding and removing validators
Create a privacy-enabled network

Updated IBFT tutorial

---

mkdocs.yml

fixed redirect

---

docs/Tutorials/Create-IBFT-Network.md

Added tip if no peers

---

.circleci/config.yml

- fix the install step that was not using `npm ci`
- refactor the file with commands to make it easier to read (change ill be don on other doc sites too)

fix and refactor CI config

---

docs/Concepts/Permissioning/PermissionsOverview.md
docs/HowTo/Configure/EnhancedPermissions.md
docs/Reference/APIs/PermissioningAPIs.md

This PR updates the permissions documentation to cover the v1 and v2 models as supported in the master branch of GoQuorum now.

permission documentation update

---

docs/Concepts/Privacy/PrivateTransactionManager.md

Documentation for the following code change: https://github.com/ConsenSys/quorum/pull/1109

Add tx manager http docs

---

docs/Concepts/Multitenancy/Overview.md
docs/Concepts/Plugins/Plugins.md
docs/HowTo/Use/Multitenancy.md
mkdocs.yml

* Support multiple tenants in a single node while preserving data isolation
* Fixes #57

Docs for multitenancy

---

mkdocs.yml

add cakeshop redirect
Test the fixed redirect at https://pegasys-docgoquorum--68.com.readthedocs.build/en/68/Cakeshop/Overview/
fixes ConsenSys/quorum#1070

add cakeshop redirect

---

docs/Concepts/Multitenancy/Overview.md
docs/Concepts/Permissioning/BasicNetworkPermissions.md
docs/Concepts/Plugins/Plugins.md
docs/HowTo/Configure/BasicPermissions.md
docs/HowTo/Configure/Consensus/Configuring-Raft.md
docs/HowTo/Configure/Plugins.md
docs/HowTo/Configure/dns.md
docs/HowTo/GetStarted/migration.md
docs/Reference/APIs/ContractExtensionAPIs.md
docs/Reference/CLI-Syntax.md
docs/Reference/Consensus/IBFTParameters.md
mkdocs.yml

Document GoQuorum CLI options.
https://pegasys-docgoquorum--72.com.readthedocs.build/en/72/Reference/CLI-Syntax/
fixes #67

add GoQuorum CLI docs

---

docs/Reference/APIs/DebugAPIs.md
mkdocs.yml

Document debug_dumpAddress. Add page for debug namespace.
fixes #40

doc debug_dumpAddress

---

docs/Reference/APIs/DebugAPIs.md

add `debug_privateStateRoot` method
Doc for ConsenSys/quorum#1148

add debug state root method

---

docs/Reference/GoQuorum-Projects.md

Update the projects page to point to the `awesome-quorum` repo (which has also been updated with the projects formerly on GoQuorum projects page).
fixes #94

update projects page

---

docs/Reference/API-Methods.md

Add note to clarify adding new roles to suborgs.
fixes #85 
see https://pegasys-docgoquorum--92.com.readthedocs.build/en/92/Reference/API-Methods/#quorumpermission_addnewrole

add note to clarify adding roles

---

docs/Tutorials/Quorum-Dev-Quickstart.md

Added a link for the quickstart walkthrough

adding a link for the quickstart walkthrough

---

docs/Reference/API-Methods.md
docs/Tutorials/Adding-removing-IBFT-validators.md

Add info to Adding IBFT Validators tutorial on using `istanbul.discard`.
fixes #102

add note on using istanbul.discard

---

docs/HowTo/Use/DevelopingSmartContracts.md
docs/Reference/API-Methods.md

Add note clarifying using RPC API without gas price. Remove gas price from examples.
fixes #99

Doc gas price is not used in goquorum networks

---

docs/Reference/CLI-Syntax.md

Doc `--raftlogdir` option.
fixes #74

doc --raftlogdir

---

docs/HowTo/Use/Revert-Reason.md
docs/Reference/CLI-Syntax.md
mkdocs.yml

Documented revertreason CLI option and added revertreason concept page
fixes #111

doc revert reason

---

docs/GetStarted/Install.md

Adds Go version recommendation to source build
Fixes #107

Go version for source build (#107)

---

docs/HowTo/Configure/Bootnodes.md
docs/HowTo/Configure/Permissioning/BasicPermissions.md
docs/HowTo/Configure/StaticNodes.md
docs/HowTo/Use/adding_nodes.md
mkdocs.yml

Add pages to define bootnodes and static nodes and how to configure them, similar to Besu docs.
fixes #151

add bootnodes and static nodes content

---

docs/Tutorials/Quorum-Dev-Quickstart/Using-the-Quickstart.md

Signed-off-by: Joshua Fernandes <joshua.fernandes@consensys.net>

updating docs for blockscout

---

docs/Concepts/Architecture.md
docs/Concepts/FreeGasNetwork.md
docs/Reference/API-Methods.md
docs/Tutorials/Contracts/Account-Funds-Transfers.md
docs/Tutorials/Contracts/Calling-Contract-Functions.md
docs/Tutorials/Contracts/Deploying-Contracts.md
docs/Tutorials/Quorum-Dev-Quickstart/Getting-Started.md
docs/Tutorials/Quorum-Dev-Quickstart/Remix.md
mkdocs.yml

Add page about free gas networks and clarify that GoQuorum is a free gas network throughout the docs.
fixes #167

add information about zero gas

---

docs/concepts/architecture.md
docs/concepts/free-gas-network.md
docs/reference/api-methods.md
docs/tutorials/contracts/account-funds-transfers.md
docs/tutorials/contracts/calling-contract-functions.md
docs/tutorials/contracts/deploying-contracts.md
docs/tutorials/quorum-dev-quickstart/getting-started.md
mkdocs.navigation.yml

Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
Add missing PRs

Add content for #172.

---

.github/workflows/pr_preview_publish.yml
docs/index.md

Updating home style using updated builder
- smaller intro font
- no illustration (profile boxes already enough)
- updated boxes text
- add more space between boxes

Update Home page

---

docs/concepts/architecture.md
mkdocs.redirects.yml

Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>
Add redirect

Add redirect.

---

docs/deploy/install/kubernetes.md

Minor edits to Kubernetes page.
fixes #179

edit kubernetes page

---

docs/deploy/upgrade/migration.md
mkdocs.navigation.yml

Add upgrade instructions for GoQuorum
Fixes: https://github.com/ConsenSys/quorum/issues/1267
Fixes: https://github.com/ConsenSys/doc.goquorum/issues/140
Fixes: https://github.com/ConsenSys/quorum/issues/1255

Update upgrade instructions

---

docs/concepts/multi-tenancy.md
docs/configure-and-manage/manage/json-rpc-api-security.md

Add examples for how to use web3j when connecting to GoQuorum when using multi-tenancy and auth.
fixes: https://github.com/web3j/web3j-quorum/issues/59

Add example connection using web3j

---

docs/deploy/upgrade/migration.md

Information about what users need to do before upgrading to v22.1.0 
https://github.com/ConsenSys/quorum/pull/1249

Add migration info for v22.1.0

---

docs/concepts/privacy/privacy-enhancements.md

Added note to privacy enhancements migration

Clarify need for geth init after changing genesis file

---

docs/global/test_accounts.md
docs/reference/genesis.md
docs/tutorials/contracts/account-funds-transfers.md

Update usage of "Mainnet for consistency"
Fixes #189

Update "Mainnet" for consistency

---

docs/reference/api-methods.md

Updates the RPC reference table of content (toc) depth for better visibility.
See https://consensys.github.io/doc.goquorum/PR-192/reference/api-methods/
----
----

update toc depth

---

.gitignore
docs/configure-and-manage/monitor/cakeshop.md
docs/tutorials/quorum-dev-quickstart/getting-started.md

Updates on how to use cakeshop with the quickstart

Updates on how to use cakeshop with the quickstart

---

.github/pull_request_template.md
docs/concepts/consensus/overview.md
docs/configure-and-manage/configure/consensus-protocols/raft.md
docs/tutorials/private-network/create-a-raft-network.md

Add warnings about using Raft only in development environments.
fixes #195 

clarify Raft usage

---

docs/reference/api-methods.md

Add missing quotes `"` in JSON code samples in the API page.
Small fix, no ticket. Was reported on Slack.

add missing quotes in json samples

---

.github/workflows/latest_publish.yml
.github/workflows/linkcheck.yml
.github/workflows/lint.yml
.github/workflows/pr_preview_delete.yml
.github/workflows/pr_preview_publish.yml
.github/workflows/release_publish.yml
.github/workflows/spelling.yml

Update the CI workflow files to use the consensys self hosted runners instead of the Github default
Saves on our plans

Update workflow to use Consensys self hosted runners

---

.github/workflows/latest_publish.yml
.github/workflows/linkcheck.yml
.github/workflows/lint.yml
.github/workflows/pr_preview_delete.yml
.github/workflows/pr_preview_publish.yml
.github/workflows/release_publish.yml
.github/workflows/spelling.yml

Reverts ConsenSys/doc.goquorum#204
Consensys self hosted runners are not available for public repositories

Revert "Update workflow to use Consensys self hosted runners"

---

docs/concepts/security-framework.md
docs/tutorials/quorum-dev-quickstart/using-the-quickstart.md

- Added notes re consortium members and validators
- Fixed quickstart new node env var

minor note re consortium members and fixup of quickstart new node

---

docs/tutorials/kubernetes/deploy-charts.md

updating k8s monitoring charts

updating k8s monitoring charts

---

docs/tutorials/contracts/account-funds-transfers.md
docs/tutorials/contracts/calling-contract-functions.md
docs/tutorials/contracts/deploying-contracts.md
docs/tutorials/quorum-dev-quickstart/using-the-quickstart.md

Editing changes for https://github.com/ConsenSys/doc.goquorum/pull/220

Enhanced permissions quickstart updates

---

docs/concepts/plugins.md

Remove test section from page
Fixes #227 

Remove debug test section

---

docs/concepts/consensus/comparing-poa.md

https://consensys.github.io/doc.goquorum/PR-232/concepts/consensus/comparing-poa/
Docs incorrectly stated that IBFT does not have immediate finality

IBFT has immediate finality

---

mkdocs.redirects.yml

Add redirects to fix broken external links
Fixes #242 

Add redirects

---

mkdocs.redirects.yml

Add a redirect for an adding nodes tutorial path indexed in the Google search console.
fixes #253 

Add redirect for adding nodes tutorial

---

docs/concepts/gas-enabled-network.md
docs/configure-and-manage/configure/consensus-protocols/qbft.md

Add documentation for block rewards, a new feature for QBFT protocol.
https://github.com/ConsenSys/quorum/commit/a20cba4105d716e4ad2aefc861eec2a3a67c7096

QBFT block rewards

---

docs/support.md
mkdocs.extra.yml

Removes reference to paid support and directs to QBS page.
Updates link in footer.
Fixes #257 

Remove references to paid support

---

docs/support.md
docusaurus.config.js

update discord links
